export interface ITopCategories {
id: any
  "categoryId": number,
  "name_L1": string,
  "name": string,
  "list": ITopCategory[]
}
interface ITopCategory {
  "id": number,
  "adsNumber": string,
  "activStatus": boolean,
  "price": number,
  "purpose": string,
  "priceInUSD": number,
  "title": string,
  "title_L1": string,
  "description": string,
  "description_L1": string,
  "slug": null,
  
  "slug_L1": null,
  "keywords": null,
  "locationName": string,
  "locationName_L1": string,
  "advertisementStatus": number,
  "created": null,
  "approvedDateTime": string,
  "contactMethod": number,
  "photos": string[],
  "flatFields": [],
  "userDisplayName": string,
  "userPhoto": string,
  "userId": string,
  "userCreateData": string,
  "isFavorite": boolean,
  "isNegotiable": boolean,
  "rejectReson": null,
  "platform": null,
  "appVersion": null,
  "longitude": null,
  "latitude": null,
  "addressDetails": null,
  "cityId": null,
  "districtId": null,
  "rating": number,
  "sold": boolean
}
